# Generated by Django 5.0.7 on 2024-07-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mahsulotlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulotlar',
            name='image',
            field=models.ImageField(upload_to='mahsulotlar/'),
        ),
    ]
