# Generated by Django 5.0.7 on 2024-07-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_mahsulotlar_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahsulotlar',
            old_name='quantity_left',
            new_name='Received',
        ),
        migrations.RenameField(
            model_name='mahsulotlar',
            old_name='quantity_received',
            new_name='Remainder',
        ),
    ]
