# Generated by Django 5.0.7 on 2024-07-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_mahsulotlar_options_alter_mahsulotlar_received_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahsulotlar',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
