# Generated by Django 5.0.7 on 2024-07-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_mahsulotlar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulotlar',
            name='Received',
            field=models.PositiveIntegerField(verbose_name='Поступлено'),
        ),
    ]
